[build]
  publish = "public"
  command = ""

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/data.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
